//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BodrumEntities : DbContext
    {
        public BodrumEntities()
            : base("name=BodrumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Item_Operation> Item_Operation { get; set; }
        public virtual DbSet<Need> Needs { get; set; }
        public virtual DbSet<Needs_OperationType> Needs_OperationType { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCommentOnItem> UserCommentOnItems { get; set; }
        public virtual DbSet<UserMobile> UserMobiles { get; set; }
    }
}
