//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Item_Operation = new HashSet<Item_Operation>();
            this.Needs_OperationType = new HashSet<Needs_OperationType>();
            this.UserCommentOnItems = new HashSet<UserCommentOnItem>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> fk_userId { get; set; }
        public Nullable<int> fk_categoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Operation> Item_Operation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Needs_OperationType> Needs_OperationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCommentOnItem> UserCommentOnItems { get; set; }
    }
}
