//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Need
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> fk_userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
